cluster:
  capi_providers:
    bootstrap_provider: cabpr

# to avoid failing the immutability check on upgrade tests:
_internal:
  previous_values:
    cluster:
      capi_providers:
        bootstrap_provider: cabpr

