apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: WORKLOAD_CLUSTER_NAMESPACE

resources:
  - ../base

# Use HA component to activate multi-nodes deployment
# components:
#   - ./high-availability

configMapGenerator:
  - name: capm3-virt-values
    files:
      - capm3-virt-values=capm3-virt-values.yaml
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: sylva-units-secrets
    behavior: merge
    files:
      - secrets=secrets.yaml
    options:
      disableNameSuffixHash: true

patches:
- target:
    kind: HelmRelease
    name: sylva-units
    namespace: WORKLOAD_CLUSTER_NAMESPACE
  patch: |
    - op: add
      path: /spec/valuesFrom/0
      value:
        kind: ConfigMap
        name: capm3-virt-values
        valuesKey: capm3-virt-values
