# this test validates that a one-shot unit for which the sylva-units-status configmap
# has NO trace that it was done, will be enabled

units:
  cluster-machines-ready:
    one_shot: true

_internal:
  _test_mockup_sylva_units_status_ConfigMap:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      annotations:
        sylva.org/ignore-migrations-from-1.1.1: ""
    data:
      additional-info: '{}'
      # one-shot-units: |
      #  cluster-machines-ready: done
      release-revision: "237"
      release-time: 2025-02-06 12:37:17.473418972 +0000 UTC m=+8852.418879350
      sylva-units-chart-version: 0.0.0-git+5eff96cd1b8e.186
      values-checksum: 50e6afccf8229411e23a06ab624af2c8e2f9a0e47dd6a6d912f5033829d384ce

  _test_unit_disabled: |
     {{- if not (include "unit-enabled" (tuple . "cluster-machines-ready")) -}}
       {{ fail "one-shot unit should be enabled (not already done)" }}
     {{- end -}}
