kind: SylvaWorkloadCluster
apiVersion: workloadclusteroperator.sylva/v1alpha1
metadata:
  name: wc1
  namespace: wc-test
spec:
  k8sVersion: "1.31"
  sylvaSourceVersion:
    tag: 1.3.10
  infrastructure: openstack
  overridingValues:
    sylva_diskimagebuilder_version: 0.4.12
    sylva_diskimagebuilder_images:
      ubuntu-noble-hardened-rke2-1-31-8:
        enabled: true
    security:
      os_images:
        skip_signing_check: true
  controlPlane:
    provider: rke2
    replicas: 1
  machineDeployments:
    my-capo-machine:
      replicas: 0
  enabledUnits:
    cinder-csi: true
    calico: true
    keycloak: false
    local-path-provisioner: true
  clusterSettings:
    capo:
      ssh_key_name: sylva-deployer   # replace me
      image_key: ubuntu-noble-hardened-rke2-1-31-8-sylva-diskimage-builder-0.4.12 # only default image is supported
      network_id: cb21c2ea-5cd3-48fd-966c-7679b1b9f269  # replace me
      flavor_name: "m1.xlarge"
      # rootVolume:
      #   diskSize: 50
      #   #volumeType: local-path
  secretValues:
    path: wc
    key: capo
