cluster:
  capi_providers:
    infra_provider: capo
    bootstrap_provider: cabpr
  control_plane_replicas: 1
  capo:
    ssh_key_name: # put the name of your nova SSH keypair here
    os_image_selector:
      os: ubuntu
      hardened: true
    network_id: # OpenStack Neutron network id on which machine will be deployed
  machine_deployments:
    md0:
      replicas: 1
      capo:
        failure_domain: region0

openstack:
  storageClass:
    name: "cinder-ceph-ssd"
    type: "ceph_ssd"
