apiVersion: v2
name: sylva-units
description: Chart to coordinate the installation of components common to the bootstrap cluster and the management cluster thanks to FluxCD resources
type: application
version: 0.0.0-git  # never used: this is ignored in git-based workflow, and overridden by git tag in the OCI artifact
appVersion: "0.0.0"
dependencies:
  - name: sylva-library
    version: 0.3.5
    repository: https://gitlab.com/api/v4/projects/56163211/packages/helm/base
