# the management cluster has all units defined in values.yaml
# (except the ones explicitly set 'enabled: false' in values.yaml
#  and not explicitely set 'enabled: false' here)
units_enabled_default: true

unit_templates:
  # this unit template gather depends_on common
  # to most units
  base-deps:
    depends_on:
      # Flux, because starting unit reconciliation while Flux is
      #       reinstalling itself proved fragile in the past
      flux-system: true
      # Kyverno and kyverno-policies, because we're introducing Kyverno policies that manage pod
      #          security settings that need to be in place before things can start up
      kyverno: true
      kyverno-policies: true

units:

  capd:
    enabled: '{{ .Values.cluster.capi_providers.infra_provider | eq "capd" }}'

  capo:
    enabled: '{{ .Values.cluster.capi_providers.infra_provider | eq "capo" }}'

  capm3:
    enabled: '{{ .Values.cluster.capi_providers.infra_provider | eq "capm3" }}'

  metal3:
    enabled: '{{ tuple . "capm3" | include "unit-enabled" }}'

  capv:
    enabled: '{{ .Values.cluster.capi_providers.infra_provider | eq "capv" }}'

  cabpk:  # kubeadm
    enabled: '{{ .Values.cluster.capi_providers.bootstrap_provider | eq "cabpk" }}'

  cabpr:  # RKE2
    enabled: '{{ .Values.cluster.capi_providers.bootstrap_provider | eq "cabpr" }}'

  cabpck:  # Canonical
    enabled: '{{ .Values.cluster.capi_providers.bootstrap_provider | eq "cabpck" }}'

  sync-openstack-images:
    depends_on:
      '{{ .Values._internal.default_storage_class_unit }}': true

  cluster-bmh:
    depends_on:
      metal3: '{{ .Values.cluster.capi_providers.infra_provider | eq "capm3" }}'
      kyverno-metal3-policies: '{{ tuple . "kyverno-metal3-policies" | include "unit-enabled" }}'

  capi-providers-pivot-ready:
    info:
      description: checks if management cluster is ready for pivot
      details: >
        This unit only has dependencies, but does not create resources.
        It is here only to have a single thing to look at to determine
        if everything is ready for pivot (see bootstrap.values.yaml pivot unit)
      internal: true
    one_shot: true  # we don't need this unit after the mgmt cluster installation is done
    unit_templates:
    - base-deps
    - dummy
    # we copy the dependencies of the 'cluster' unit
    # (with the exception of "capo-cluster-resources" which we don't need, given how what it produces is consumed)
    depends_on: '{{ omit .Values.units.cluster.depends_on "capo-cluster-resources" "cluster-bmh" | include "preserve-type" }}'

  cluster:
    depends_on:
      # these dependencies are set here rather than in values.yaml, because slightly different ones
      # need to be declared for workload clusters in workload-cluster.values.yaml
      capi: true
      '{{ .Values.cluster.capi_providers.infra_provider }}': true
      '{{ .Values.cluster.capi_providers.bootstrap_provider }}': true
      kyverno-policies: '{{ .Values.cluster.capi_providers.infra_provider | eq "capm3" }}'
      os-image-server: '{{ .Values.cluster.capi_providers.infra_provider | eq "capm3" }}'
      # we need this unit to be upgraded before 'cluster' unit during the upgrade to Sylva 1.2:
      # this line can be removed after the release of Sylva 1.2 (but it won't cause harm if we keep it)
      kyverno-policy-prevent-mgmt-cluster-delete: '{{ and (tuple . "kyverno-policy-prevent-mgmt-cluster-delete" | include "unit-enabled") (.Values._internal.state.is_upgrade) }}'
      # related to the above: we need to ensure that the new policy defined in the unit
      # mentioned above is ready before we update 'cluster' unit
      kyverno-policies-ready: '{{ and (tuple . "kyverno-policies-ready" | include "unit-enabled") .Values._internal.state.is_upgrade }}'

  calico-ready:
    enabled: '{{ .Values._internal.state.is_upgrade }}'
    # we'll use the kustomization_spec.kubeConfig.secretRef from values.yaml definition
    # but that's fine, since secret is present once pivot happened
    # otherwise we'd need to nullify it here and define it also in bootstrap.values.yaml

  # Temporary workaround until DriftDetection is fully enabled
  # see https://gitlab.com/sylva-projects/sylva-core/-/issues/1840
  refresh-metal3machinetemplates:
    info:
      description: Recreate metal3machinetemplates resources via the reconciliation of cluster helmrelease
      internal: true
    unit_templates:
    - base-deps
    - kube-job
    enabled_conditions:
    - '{{ tuple . "metal3" | include "unit-enabled" }}'
    - '{{ tuple . "cluster" | include "unit-enabled" }}'
    - '{{ not .Values._internal.state.is_upgrade }}'
    depends_on:
      cluster: true
      cluster-machines-ready: true
    kustomization_spec:
      _patches:
      - target:
          kind: ConfigMap
          labelSelector: kube-job=script
        patch: |
          - op: replace
            path: /data/kube-job.sh
            value: |
              #!/bin/bash
              set -e
              kubectl patch cluster.cluster.x-k8s.io {{ .Values.cluster.name }} --type merge -p '{"spec":{"paused": true}}'
              deployed_version=$(kubectl get helmrelease cluster -o jsonpath='{.status.history[?(@.status=="deployed")].version}')
              let deployed_version+=1
              echo "-- metal3machinetemplates before deletion"
              kubectl get m3mt
              kubectl delete m3mt --all -n sylva-system
              kubectl annotate --overwrite helmrelease/cluster reconcile.fluxcd.io/requestedAt="$(date -uIs)" reconcile.fluxcd.io/forceAt="$(date -uIs)"
              kubectl wait helmrelease cluster --for='jsonpath={.status.history[?(@.status=="deployed")].version}='$deployed_version
              kubectl wait helmrelease cluster --for condition=Ready
              echo "-- metal3machinetemplates after helmrelease cluster reconciliation"
              kubectl get m3mt
              kubectl patch cluster.cluster.x-k8s.io {{ .Values.cluster.name }} --type merge -p '{"spec":{"paused": false}}'

  kyverno-policy-prevent-mgmt-cluster-delete:
    info:
      description: Kyverno policies to prevent deletion of critical resources for mgmt cluster
      internal: true
    enabled_conditions:
    - '{{ tuple . "kyverno" | include "unit-enabled"  }}'
    depends_on:
      kyverno: true
      capi: true
    unit_templates:
    - base-deps
    repo: sylva-core
    kustomization_spec:
      path: ./kustomize-units/kyverno-policies/prevent-mgmt-cluster-delete
      wait: true

  os-image-server:
    enabled: '{{ tuple . "metal3" | include "unit-enabled" }}'

  kubevirt:
    enabled: false

  kubevirt-test-vms:
    enabled: false

  prometheus-custom-metrics:
    depends_on:
      monitoring-crd: true

  sylva-prometheus-rules:
    helmrelease_spec:
      values:
        createRules:
          # always add the management-cluster rules
          # regardless of the management cluster name
          management-cluster: true

  monitoring:
    depends_on:
      keycloak-oidc-external-secrets: true
      keycloak-add-realm-role: true
      grafana-init: true
    annotations:
      sylvactl/readyMessage: "Grafana UI can be reached at https://{{ .Values.external_hostnames.grafana }} ({{ .Values.external_hostnames.grafana }} must resolve to {{ .Values.display_external_ip }})"
    helmrelease_spec:
      values:
        defaultRules:
          rules:
            kubeApiserverSlos: false
            kubeStateMetrics: false
            kubernetesApps: false
            kubernetesResources: false
            kubernetesStorage: false
            kubernetesSystem: false
            network: false
            nodeExporterAlerting: false
        grafana:
          envFromSecret: grafana-oidc
          sidecar:
            datasources:
              isDefaultDatasource: false
          grafana.ini:
            server:
              root_url: 'https://{{ .Values.external_hostnames.grafana }}'
            auth.anonymous:
              enabled: false
            auth.generic_oauth:
              enabled: true
              name: Keycloak-OAuth
              scopes: openid email profile offline_access roles
              email_attribute_path: email
              login_attribute_path: username
              name_attribute_path: full_name
              client_id: grafana
              auth_url: 'https://{{ .Values.external_hostnames.keycloak }}/realms/sylva/protocol/openid-connect/auth'
              token_url: 'https://{{ .Values.external_hostnames.keycloak }}/realms/sylva/protocol/openid-connect/token'
              api_url: 'https://{{ .Values.external_hostnames.keycloak }}/realms/sylva/protocol/openid-connect/userinfo'
              role_attribute_path: contains(roles[*], 'grafanaadmin') && 'Admin' || contains(roles[*], 'grafanaeditor') && 'Editor' || contains(roles[*], 'grafanaviewer') && 'Viewer' || 'None'
              allow_assign_grafana_admin: true
              groups_attribute_path: groups
              use_refresh_token: true
              signout_redirect_url: 'http://{{ .Values.external_hostnames.keycloak }}/realms/sylva/protocol/openid-connect/logout'
          extraSecretMounts:
            - name: grafana-ca
              mountPath: "/etc/ssl/certs"
              secretName: sylva-ca.crt
          # Define a custom ingress to directly access Grafana without nginx path rewrite
          # see https://gitlab.com/sylva-projects/sylva-core/-/issues/1622
          extraObjects:
          - apiVersion: v1
            kind: Service
            metadata:
              name: grafana-sylva-service
              namespace: cattle-monitoring-system
            spec:
              type: ClusterIP
              ports:
              - name: grafana-http
                port: 80
                protocol: TCP
                targetPort: 3000
              selector:
                app.kubernetes.io/instance: rancher-monitoring
                app.kubernetes.io/name: grafana
          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: grafana-sylva-ingress
              namespace: cattle-monitoring-system
            spec:
              ingressClassName: nginx
              tls:
              - secretName: grafana-tls
                hosts:
                - '{{ .Values.external_hostnames.grafana }}'
              rules:
              - host: '{{ .Values.external_hostnames.grafana }}'
                http:
                  paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: grafana-sylva-service
                        port:
                          number: 80
        global:
          cattle:
            clusterId: local
            clusterName: local
    helm_secret_values:
      grafana:
        # https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file
        additionalDataSources:
          - name: Thanos
            type: "prometheus"
            access: "proxy"
            url: "http://thanos-query-frontend.thanos:9090"
            basicAuth: true
            basicAuthUser: '{{ .Values._internal.thanos_user }}'
            jsonData:
              tlsSkipVerify: true
              timeInterval: 60s
              prometheusVersion: "0.35.0"
              customQueryParameters: "deduplicate=1&max_source_resolution=auto"
            secureJsonData:
              basicAuthPassword: '{{ .Values._internal.thanos_password }}'
            isDefault: true
          - name: Loki
            type: "loki"
            access: "proxy"
            url: '{{ .Values.logging.loki_url }}'
            basicAuth: true
            basicAuthUser: '{{ .Values._internal.loki_user }}'
            jsonData:
              tlsSkipVerify: true
            secureJsonData:
              basicAuthPassword: '{{ .Values._internal.loki_password }}'

  logging:
    depends_on:
      loki: '{{ tuple . "loki" | include "unit-enabled" }}'

  loki:
    enabled: '{{ tuple . "logging" | include "unit-enabled" }}'

  snmp-exporter:
    enabled: '{{ tuple . "capm3" | include "unit-enabled" }}'

  harbor-init:
    depends_on:
      sylva-ca: true
      keycloak-resources: true
      kyverno: true
      vault: true
      vault-config-operator: true
      eso-secret-stores: true
      keycloak-add-client-scope: true

  harbor:
    depends_on:
      harbor-init: true
    helmrelease_spec:
      _postRenderers:
        - kustomize:
            patches:
              - patch: |-
                  kind: Deployment
                  apiVersion: apps/v1
                  metadata:
                    name: harbor-core
                  spec:
                    template:
                      spec:
                        containers:
                          - name: core
                            env:
                              - name: CONFIG_OVERWRITE_JSON
                                valueFrom:
                                  secretKeyRef:
                                    key: CONFIG_OVERWRITE_JSON
                                    name: "harbor-oidc"

  management-flag:
    info:
      internal: true
      description: dummy unit to identify management cluster
      details: >
        This unit will produce a configmap in management cluster that can be used by apply scripts
        to assert that they are properly targeting the management cluster
    enabled: true
    unit_templates:
    - dummy

  sylva-ca:
    depends_on:
      external-secrets-operator: true
    kustomization_spec:
      postBuild:
        substitute:
          CA_NAME: 'sylva-selfsigned-ca'
          CA_COMMON_NAME: 'Sylva CA'
          CA_O_NAME: 'Sylva'
      _components:
        - components/eso
        - '{{ tuple "components/acme-issuer" (eq .Values.security.external_x509_issuer.issuer_type "acme") | include "set-only-if" }}'
        - '{{ tuple "components/vault-issuer" (eq .Values.security.external_x509_issuer.issuer_type "vault") | include "set-only-if"}}'
        - '{{ tuple "components/ca-issuer" (not (hasKey .Values.security.external_x509_issuer "issuer_type")) | include "set-only-if" }}'

  cluster-import-legacy-cleanup:
    info:
      description: Remove resources used by capi-rancher-import
      details: >
        a job to manually delete the secret used in the legacy solution
      internal: true
    one_shot: true
    enabled_conditions:
    - '{{ .Values._internal.state.is_upgrade }}'
    depends_on:
      cluster-ready: '{{ tuple . "cluster" | include "unit-enabled" }}'
    unit_templates:
    - kube-job
    - base-deps
    kustomization_spec:
      _patches:
      - target:
          kind: ConfigMap
          labelSelector: kube-job=script
        patch: |
          - op: replace
            path: /data/kube-job.sh
            value: |
              #/bin/bash
              set -e
              kubeconfig_secret_user_b64=$(kubectl -n sylva-system get secret cluster-creator-kubeconfig -o jsonpath='{.data.USER_NAME}' 2>/dev/null || true)
              if [[ $kubeconfig_secret_user_b64 != "" ]]; then
                 echo "cluster-creator-kubeconfig Secret found"
                 user=$(echo $kubeconfig_secret_user_b64 | base64 -d)
                 echo "Delete cluster-creator-kubeconfig Rancher user $user"
                 kubectl delete users.management.cattle.io $user --ignore-not-found=false
                 echo "Delete secret related to legacy solution"
                 kubectl -n sylva-system delete secret cluster-creator-kubeconfig
              else
                 echo "No legacy resources (no cluster-creator-kubeconfig Secret)"
              fi
      - target:
          kind: ClusterRole
        patch: |
          - op: replace
            path: /rules
            value:
              - apiGroups: [management.cattle.io]
                resources: [users]
                verbs: [list, delete]

keycloak:
  keycloak_expire_password_days: 30

cluster:
  prevent_deletion: true
  capo:
    flavor_name: m1.xlarge

_internal:
  mgmt_cluster: true

  calico_readiness_unit: '{{ .Values._internal.state.is_upgrade | ternary "calico-ready" "calico" }}'

  monitoring:
    conditionals:
      # Always deploy management cluster Longhorn resources, so that the dashboard
      # is available to observe Longhorn metrics of any workload cluster
      longhorn:
        enabled: 'true'
