{{- $envAll := set . "Values" (include "interpret-values-gotpl" . | fromJson) -}}
apiVersion: v1
kind: Secret
metadata:
  name: cosign-public-keys
type: Opaque
data:
  cosign.pub: {{ $envAll.Values.security.oci_artifacts.cosign_public_key  | b64enc }}
