  # this is used for testing charts/sylva-units/templates/sylva-units-values.yaml logic based on default
  # ._internal.immutable_values and expected to fail given the default `.cluster.name: management-cluster` value
_internal:

  previous_values:
    cluster:
      name: old-management-cluster
      cluster_virtual_ip: 192.18.0.100
    default_storage_class: cinder-csi
